name: Docker Image Build

# Need manually created
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# DOCKERHUB_IMAGE_NAME

on:
  push:
    branches: [ 'debian-dockerfile' ] #rolling build on develop only
    tags: 'v*' #tag for specific release v1.0.2,or anytag, start with v
  pull_request:
    branches: [ 'main' ] #build test on main, not pushing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build and Push amd64 first
        uses: docker/build-push-action@v3
        with:
          context: .
          push:  ${{ github.event_name != 'pull_request' }} #push except PR.
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:git
          labels: ${{ steps.metaid.outputs.labels }}
          file: Dockerfile
          
      - name: Build and Push repack
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} #push except PR.
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:git
          labels: ${{ steps.metaid.outputs.labels }}
          file: Dockerfile.repack

